version: '3'
services:
  web:
    build: .
    ports:
     - 5000:5000
    volumes:
     - ./app
    links:
     - db:postgres
    depends_on:
     - db
  db:
    hostname: postgres
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"